"""Regenerate docs/DATA_SOURCES.md from the registry, so it cannot drift.

    python -m workers.ingestion.build_docs
"""
from __future__ import annotations

import sys

from workers.ingestion.common import (
    DATA, REGISTRY_DIR, SCHEDULES_DIR, iso_utc, read_json,
)

DOC = DATA.parent / "docs" / "DATA_SOURCES.md"

COVERAGE_MEANING = {
    "feeder": "Detailed — feeder-level schedule available",
    "division": "Partial — division/office schedule, feeder mapping incomplete",
    "utility": "Limited — utility-wide notices only",
    "unknown": "Unavailable — no verified public schedule source",
}


def main() -> int:
    reg = read_json(REGISTRY_DIR / "sources.json", {}) or {}
    utils = (read_json(REGISTRY_DIR / "utilities.json", {}) or {}).get("utilities", [])
    index = (read_json(SCHEDULES_DIR / "index.json", {}) or {}).get("utilities", [])
    alerts = (read_json(REGISTRY_DIR / "official-alerts.json", {}) or {})
    sources = reg.get("sources", [])
    rows = {r["utility"].upper(): r for r in index}

    out: list[str] = []
    w = out.append

    w("# Data sources\n")
    w("> Generated by `python -m workers.ingestion.build_docs` on %s.\n"
      "> Status and TLS columns are what the probe **observed**, not what we assume.\n" % iso_utc())

    s = reg.get("summary", {})
    w("\n**%s of %s registered sources reachable · %s have a parser · %s served a valid TLS chain**\n"
      % (s.get("reachable", "?"), s.get("total", len(sources)),
         s.get("with_parser", "?"), s.get("tls_chain_ok", "?")))

    # ---- coverage matrix
    w("\n## Coverage matrix\n")
    w("| Distributor | Coverage | Claims live | Parser | What exists |")
    w("|---|---|---|---|---|")
    for u in utils:
        uid = str(u["id"]).upper()
        row = rows.get(uid, {})
        mine = [x for x in sources if str(x["utility"]).upper() == uid]
        parsers = sorted({x["parser_adapter"] for x in mine if x.get("parser_adapter")})
        level = row.get("coverage_level") if row.get("status") == "fresh" else (
            "division" if any(x.get("coverage_level") == "feeder" for x in mine)
            else "utility" if mine else "unknown")
        w("| **%s** | %s | %s | %s | %s |" % (
            u["name"],
            COVERAGE_MEANING.get(level, COVERAGE_MEANING["unknown"]),
            "{:,}".format(row.get("claim_count", 0)),
            ", ".join("`%s`" % p for p in parsers) if parsers else "—",
            (row.get("message") or u.get("coverage_description", ""))[:130]))

    # ---- per source
    w("\n## Registered sources\n")
    for u in utils:
        uid = str(u["id"]).upper()
        mine = [x for x in sources if str(x["utility"]).upper() == uid]
        if not mine:
            continue
        w("\n### %s — %s\n" % (u["name"], u.get("full_name", "")))
        if u.get("coverage_description"):
            w("%s\n" % u["coverage_description"])
        w("\n| Source | Format | Coverage | Updates | Status | TLS |")
        w("|---|---|---|---|---|---|")
        for x in mine:
            w("| [%s](%s) | %s | %s | %s | %s | %s |" % (
                x["title"], x["source_url"],
                x.get("observed_format") or x.get("format", "?"),
                x.get("coverage_level", "?"),
                x.get("expected_update_frequency", "?"),
                x.get("http_status", "?"),
                "ok" if x.get("tls_ok") else "chain unverified"))
        for x in mine:
            if x.get("notes"):
                w("\n- **%s** — %s" % (x["title"], x["notes"]))
        divisions = u.get("divisions") or []
        if divisions:
            w("\n<details><summary>%d known divisions/zones</summary>\n\n%s\n\n"
              "*Source: %s*\n</details>" % (
                  len(divisions), ", ".join(divisions), u.get("divisions_source", "unknown")))

    # ---- contact routes
    w("\n## Official notification routes\n")
    uni = alerts.get("unified") or {}
    if uni:
        w("**Unified call centre `%s`** — %s\n" % (uni.get("hotline"), uni.get("description", "")))
    w("\n| Distributor | Hotline | Website | How the number was verified |")
    w("|---|---|---|---|")
    for a in alerts.get("alerts", []):
        w("| %s | %s | %s | %s |" % (
            a["utility"],
            ", ".join("`%s`" % h for h in (a.get("hotline") or [])) or "—",
            a.get("website_url") or "—",
            a.get("hotline_verified_from") or "not verified"))

    # ---- blockers
    w("\n## Known blockers\n")
    w("1. **DPDC uses a legacy non-Unicode Bengali font.** Feeder codes, MW loads and the hour grid\n"
      "   extract cleanly, but area names come out as mojibake, so no adapter is enabled. Decoding\n"
      "   the Bijoy/ASCII mapping is the single highest-value unblock after DESCO.\n")
    w("2. **NESCO publishes scans.** Zero extractable text; OCR on Bangla scans is not reliable\n"
      "   enough to publish without human review.\n")
    w("3. **BREB has no national feed.** Around 80 Palli Bidyut Samity cooperatives publish\n"
      "   independently, which is ~80 adapters, not one.\n")
    w("4. **URLs move without notice.** DPDC's schedules live on `dpdc.org.bd`, not the\n"
      "   `dpdc.gov.bd` corporate site, and its zone PDFs carry an incrementing revision counter in\n"
      "   the filename. Always scrape the index; never hardcode a document URL.\n")

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print("wrote %s (%d lines)" % (DOC, len(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
